apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherry-ui
  labels:
    app: cherry-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cherry-ui
  template:
    metadata:
      labels:
        app: cherry-ui
    spec:
      containers:
        - name: cherry-ui
          image: uherman/cherry-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SOME_VAR
              value: 'some value'
---
apiVersion: v1
kind: Service
metadata:
  name: cherry-ui
spec:
  type: NodePort
  selector:
    app: cherry-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
